# Site settings
title: Sioryn Willett
email: sinwillett@gmail.com
description: > 
  Sioryn willett's test site.
baseurl: "/test-pages"
url: "http://sin-willett.github.io" # the base hostname & protocol for your site
theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
